### ISSUE TITLE
Index.html is not up to date

### ISSUE THREAD

**Issue by rajeshboda** [RameshMF/registration-login-spring-boot-security-thymeleaf-hibernate#1]
Hi @RameshMF ,

Thanks for the wonderful tutorial. It helps to kick start spring boot journey. 
I think you haven't copied the index.html correctly in the git. It just has some random data.
I also have a question on _Welcome <span sec:authentication="principal.username"> User</span>_

This always prints user email. I search for it in google to get user first name instead of email, Can you suggest if this doable?

Thanks,
Rajesh.

**Comment by rajeshboda** [comment]
Created PR https://github.com/RameshMF/registration-login-spring-boot-security-thymeleaf-hibernate/pull/2

**Comment by RameshMF** [comment]
I have updated the index.html file with the required stuff.

**Comment by RameshMF** [comment]
Thanks for reporting.
